### PR TITLE
Support input[type=text]

### PR DESCRIPTION
**Pull request by pafcu**
Seems to work fine with normal text inputs.

### CODE REVIEW

**Comment by yuku-t** [comment]
Hi @pafcu, thanks for the patch.
Sorry for my late reply. I don't have enough time to check the behavior. Can you show me a screenshot which shows the plugin working with `input[type=text]`?

**Comment by pafcu** [comment]
test1

**Comment by pafcu** [comment]
I also added support for fixed input elements now. See https://github.com/yuku-t/jquery-textcomplete/issues/151.

**Comment by yuku-t** [comment]
LGTM thanks

**Comment by pafcu** [comment]
Thanks for merging! I noticed that the combined JS in dist also needs updating. Should I submit a new pull request for that, or will you do it?

**Comment by yuku-t** [comment]
I'll do it. :)

**Pull request merged**
