### PR TITLE
Support input[type=search]

### PR DESCRIPTION
**Pull request by bhollis**
Pretty simple change! I have a local copy of this and it works great on search inputs.

### CODE REVIEW

**Comment by yuku-t** [comment]
LGTM :octocat:

**Comment by bhollis** [comment]
Awesome! Let me know when this is released and I can replace my local copy w/ a bower copy.

**Comment by yuku-t** [comment]
@bhollis v1.2.0 is released :tada:

**Comment by bhollis** [comment]
Thank you!

**Comment by bhollis** [comment]
Hmm, 1.2.0 doesn't seem to have the updates in its `dist` folder.

**Comment by yuku-t** [comment]
@bhollis oops! I released v1.2.1 :sweat:

**Pull request merged**
