### PR TITLE
Feature ckeditor

### PR DESCRIPTION
**Pull request by amenk**
see https://github.com/yuku-t/textcomplete/issues/35 and so on

### CODE REVIEW

**Comment by yuku-t** [comment]
I've merged #252. Can you rebase to the current master?

**Comment by amenk** [comment]
With or without dist?

**Comment by yuku-t** [comment]
without dist :)

**Comment by amenk** [comment]
Rebasing is fun! :-) Here you go.

**Comment by amenk** [comment]
I did frontend tests on IE10, 11, FF 46, Chrome 50, Opera 37 with EasyRedmine (CKEditor with the Tabs plugin on - that inserts spaces on the press of the tab key)

**Comment by yuku-t** [comment]
> I did frontend tests on IE10, 11, FF 46, Chrome 50, Opera 37 with EasyRedmine

Thanks :+1:

**Pull request merged**
