### PR TITLE
Remove LTR Embedding for RTL Languages

### PR DESCRIPTION
**Pull request by lpsBetty**
sorry for the second PR, but I think people who read from right to left maybe are used to text segments with latin characters, so I would not use the unicode character for LEFT-TO-RIGHT EMBEDDING. 

for example my autocomplete value was ``%{count}``

with embedding it was shown: ``%{count}``
without it is shown: ``{count}%``

and I think the second one is more readable for people you read RTL languages..

### CODE REVIEW

**Comment by yuku-t** [comment]
Why not revert 7cff399869acc93f99f87c863f2ecfc6cb96012b ?

**Comment by lpsBetty** [comment]
because the one bugfix is in it, there was a JS error!

**Comment by yuku-t** [comment]
ic.
As you did at #192 , please run build task. then I'll merge this.

**Comment by lpsBetty** [comment]
sorry I updated my commit, now it is build!
thank you very much.

**Comment by yuku-t** [comment]
thx

**Comment by lpsBetty** [comment]
Thank you, sorry for the inconvenience, at least I fixed a bug!
When do you plan updating the version and therefor the bower/npm package?

**Comment by yuku-t** [comment]
done

**Pull request merged**
